spring:
  application:
    name: Api-Gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
          - id: api-1
            uri: lb://welcome
            predicates:
              - Path=/welcome
          - id: api-2
            uri: lb://greet
            predicates:
              - Path=/greet
server:
  port: 4444